stages:
  - test
  - delivery


test-job:
  stage: test
  script:
    - docker-compose -f docker/test/docker-compose.yml down
    - docker-compose -f docker/test/docker-compose.yml build api
    - docker-compose -f docker/test/docker-compose.yml up --abort-on-container-exit

delivery-job:
  stage: delivery
  script:
    - echo -n "$DOCKER_REGISTRY_KEY" | docker login --username "$DOCKER_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker tag cityheroes-api:test $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE
