version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=cityheroes
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=nik140406
    volumes:
      - mysql_data:/var/lib/mysql/

  redis: 
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
#    image: itsoda14/cityheroes-api:1.2
    environment:
      - DJANGO_RUNNING_IN_DOCKER=True
    ports:
      - "8000:8000" 
    depends_on:
      - mysql
      - redis 
    volumes:
      - .:/cityheroes
    container_name: django-api

volumes:
  mysql_data: null
