version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nik140406
      MYSQL_DATABASE: CityHeroes  # Замените на ваше название базы данных

  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: 
      - bash
      - -c
      - |
        poetry run python manage.py migrate
        poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"  # Поменяйте порт, если это необходимо
    depends_on:
      - db
    volumes:
      - .:/cityheroes  # Замените это на путь к вашему Django проекту внутри контейнера
