version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nik140406
      MYSQL_DATABASE: CityHeroes  # Замените на ваше название базы данных
    volumes:
      - mysql_data:/var/lib/mysql

  redis: 
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  api:
    image: itsoda14/cityheroes-api:api
    command: 
      - bash
      - -c
      - |
        poetry run python manage.py migrate
        poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"  # Поменяйте порт, если это необходимо
    depends_on:
      - db
      - redis 
    volumes:
      - .:/cityheroes  # Замените это на путь к вашему Django проекту внутри контейнера
